movableink/fluid

- .github/workflows/ci.yml
- package.json
Why
---
Adding Percy to CI process
> feat: added percy to ci

- addon/components/fluid-drawer.hbs
- app/styles/fluid/components.scss
- app/styles/fluid/popups.scss
PRs
https://github.com/movableink/front-end/pull/7343
https://github.com/movableink/front-end/pull/7309
Co-authored-by: Russell Tepper <rtepper@movableink.com>
Co-authored-by: Jess Wallin <jwallin@movableink.com>
> refactor: migrating all latest front-end/fluid changes

- app/styles/fluid/components/fluid-tooltip.scss
- tests/integration/components/fluid-tooltip-test.js
[sc-62231](https://app.shortcut.com/movableink/story/62231/ui-bug-layer-with-sms-flag-should-be-visible)
> fix: adjusted tooltip z-index

- .github/workflows/release-it.yml
BREAKING CHANGE: all master merges will be deployed using
conventional commits as log
> feat!: auto deploy on master merge

- .env
- .github/workflows/deploy.yml
- .storybook/main.js
> Revert "fix: storybook is not building properly"

- addon/components/fluid-select/docs.mdx
- addon/components/fluid-select/index.stories.jsx
Added some missing docs
[🎟️ [sc-64534]](https://app.shortcut.com/movableink/story/64534/fluid-select-add-missing-type-to-storybook)
> feat: added multiple story for select

- package.json
- yarn.lock
- This can allow command injection
- [sc-66420]
> fix(security): shell-quote has been flagged <1.7.2

- .storybook/preview-head.html
- addon/components/fluid-button-groups/docs.mdx
- addon/components/fluid-button/docs.mdx
- addon/components/fluid-checkbox/docs.mdx
- addon/components/fluid-radio-button/docs.mdx
- addon/components/fluid-text-input/fluid-text-input.docs.mdx
- addon/components/fluid-text-input/fluid-text-input.stories.jsx
[sc-64627](https://app.shortcut.com/movableink/story/64627/fluid-text-input-visual-examples)
[sc-64635](https://app.shortcut.com/movableink/story/64635/fluid-radio-button-visual-example)
> Updated some missing and broken documentation:

- addon/components/fluid-tooltip/fluid-tooltip.docs.mdx
[sc-64639](https://app.shortcut.com/movableink/story/64639/fluid-tooltip-docs-example-more-space)
> fix(style): added more height to tooltip

- addon/components/fluid-text-input/fluid-form-field.docs.mdx
- addon/components/fluid-text-input/fluid-form-field.stories.jsx
- tests/dummy/app/styles/app.scss
There were a few missing examples for the fluid form field.
[sc-64623](https://app.shortcut.com/movableink/story/64623)
> Fluid Form Field - Examples

- .gitignore
- CODEOWNDERS
- added storybook generated file to ignore
> chore(config): updated PR assignment

- .gitignore
- addon/components/fluid-select/docs.mdx
- addon/components/fluid-select/index.stories.jsx
Added missing search example for stories
[sc-64636](https://app.shortcut.com/movableink/story/64636/fluid-select-searching-example)
> Fluid select - searching example

- addon/components/fluid-select/docs.mdx
- addon/components/fluid-select/index.stories.jsx
[sc-64637](https://app.shortcut.com/movableink/story/64637/fluid-select-block-example)
> chore(docs): added block example

- package.json
- yarn.lock
> Revert "chore(deps-dev): bump sinon from 10.0.0 to 15.0.0"

- package.json
- yarn.lock
> Revert "chore(deps-dev): bump ember-template-lint-plugin-prettier from 2.0.1 to 3.0.1"

- package.json
- yarn.lock
Security patch for tailwind config
> chore(deps): tailwind config

- .storybook/preview-head.html
- addon/components/fluid-drawer.hbs
- app/styles/fluid/components/on-off-switch.scss
- package.json
- yarn.lock
This is for our august release bumping version of tailwind-config
> Nicksteffens/sc 86339/tailwind config/color updates

- addon/components/fluid-modal.hbs
After color updates the modal footer was a bit dark as requested by @Allisonsasso 
[sc-89974]
> style: lighten fluid modal footer color

- app/styles/fluid/functional-components/fluid-panel.scss
- app/styles/fluid/functional-components/fluid-table.scss
More color fixes for the August 2023
[sc-89974]
> style: table header colors and border color

- addon/components/fluid-drawer.hbs
These are additional style issues we've located post major launch.
> style: update fluid drawer bg

- .storybook/preview-head.html
- package.json
- yarn.lock
Updates the `fluid-button` basic to have outline
> chore(deps): bump tailwind-config to 3.1.1

- addon/components/fluid-drawer.hbs
- app/styles/fluid/components/fluid-checkbox.scss
additional style updates for 
https://github.com/movableink/front-end/pull/7970
> Additional InkUX tailwind updates

- addon/components/fluid-select/search.hbs
- app/styles/fluid/components/fluid-select.scss
support work for https://github.com/movableink/front-end/pull/7970
> Inkux - Updates
